Repository janniksam/Akinator.Api.Net, pull requests merged in 2020-04, with the labels that each got.

#16 ported to net standard 1.4
  Akinator.Api.Net.Example/Akinator.Api.Net.Example.csproj
  Akinator.Api.Net.Tests/Akinator.Api.Net.Tests.csproj
  Akinator.Api.Net/Akinator.Api.Net.csproj
  Akinator.Api.Net/Utils/StringExtensions.cs
  README.md
Labels: upgradement

#18 Improving GuessIsDue method
  Akinator.Api.Net.Example/Program.cs
  Akinator.Api.Net.Tests/ClientIntegrationTests.cs
  Akinator.Api.Net.Tests/GuessDueCheckerTests.cs
  Akinator.Api.Net/AkinatorClient.cs
  Akinator.Api.Net/Enumerations/Platform.cs
  Akinator.Api.Net/IAkinatorClient.cs
  Akinator.Api.Net/Utils/GuessDueChecker.cs
  README.md
Labels: Improvement

#19 Automatic Server Location
  Akinator.Api.Net.Example/Program.cs
  Akinator.Api.Net.Tests/Akinator.Api.Net.Tests.csproj
  Akinator.Api.Net.Tests/AkinatorServerLocatorIntegrationTest.cs
  Akinator.Api.Net.Tests/ClientIntegrationTests.cs
  Akinator.Api.Net/Akinator.Api.Net.csproj
  Akinator.Api.Net/AkinatorClient.cs
  Akinator.Api.Net/AkinatorServer.cs
  Akinator.Api.Net/AkinatorServerLocator.cs
  Akinator.Api.Net/Enumerations/Language.cs
  Akinator.Api.Net/Enumerations/ServerType.cs
  Akinator.Api.Net/IAkinatorClient.cs
  Akinator.Api.Net/IAkinatorServer.cs
  Akinator.Api.Net/IAkinatorServerLocator.cs
  Akinator.Api.Net/Model/External/ServerSearchResult.cs
  Akinator.Api.Net/Model/External/ServerSearchResultCandidats.cs
  Akinator.Api.Net/Model/External/ServerSearchResultCapsDisabled.cs
  Akinator.Api.Net/Model/External/ServerSearchResultInstance.cs
  Akinator.Api.Net/Model/External/ServerSearchResultLanguage.cs
  Akinator.Api.Net/Model/External/ServerSearchResultParameters.cs
  Akinator.Api.Net/Model/External/ServerSearchResultSubject.cs
  Akinator.Api.Net/Model/Server.cs
  Akinator.Api.Net/Utils/AkiUrlBuilder.cs
  Akinator.Api.Net/Utils/AkiWebClient.cs
  Akinator.Api.Net/Utils/ServerSelector.cs
  README.md
Labels: enhancement
